# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\\Users\\macebal\\Desktop\\Python\\GUI\\AutoSiqual v2\\log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_LogWindow(object):
    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.resize(570, 160)
        self.centralwidget = QtWidgets.QWidget(LogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log_text_edit.setGeometry(QtCore.QRect(10, 5, 550, 146))
        self.log_text_edit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.log_text_edit.setObjectName("log_text_edit")
        LogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)

    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "Log"))
