name: test
run-name: Run unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Install dependencies
      run: make install
    - run: ls -R 
    - run: python -c "import sys; sys.path.insert(0, './src')"
    - name: Run tests
      run: make test
