name: test
run-name: Run unit tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Do not let Poetry to install again if we do not detect a lock file change
      - name: Load cached venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |          
          poetry install --no-interaction --all-extras

      - name: Run test scripts
        run: |
          poetry run pytest