name: test
run-name: Run unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Create virtual environment, install dependencies and run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        make install
        make test